### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by vmaskmovps** [ad1mt/Multi-Word-Int#8]
If you're leaving your documentation as an .odt (which you haven't updated in 7 months), it might as well be a binary blob. Have a proper documentation file in plain text (or Markdown, or using the various other plain-text formats), or at least give a .pdf of the ODT. Nobody wants to install MS Word or LibreOffice just to read a file, and your documentation can really just be a text file (yes, I've taken a look at it).

**Comment by lucyfrost661** [comment]
[overanalytcl](https://github.com/overanalytcl): What a small-minded comment! You use the word 'proper' as a synonym for 'the way I do things'.

**Comment by overanalytcl** [comment]
How does that nullify the concern raised in this issue (i.e. having plain
text documentation that everyone can read, not just those with a .odt
viewer)? Inspired by you, I'll write the docs for my next project in a
slideshow embedded in an executable, because you don't seem to be concerned
about a supposedly public domain repo having easily accessible
documentation.

mie., 9 oct. 2024, 03:22 lucyfrost661 ***@***.***> a scris:

**Comment by vmaskmovps** [comment]
It seems you've moved the documentation to a .txt file, so I'll close this issue. @ad1mt
